### ISSUE TITLE
debug guide?

### ISSUE THREAD

**Issue by aca** [IngoMeyer441/tmux-easy-motion#1]
Thanks for the great plugin.
But I'm having trouble making it work at all. 
Not sure where to start, how can i debug this?

```
$ tmux -V
tmux 3.1c

#$ uname -a
Darwin rok 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64 i386 MacBookPro16,1 Darwin
```

**Comment by IngoMeyer441** [comment]
Thanks for trying my extension. To be honest, I did not run any tests on macOS yet since I have no Mac I could run tests on (currently). Do you get any messages or can you describe what happens? I could also add the option to write debug output to a temporary file.

**Comment by aca** [comment]
@IngoMeyer441 
Nothing happens, just doesn't work. It seems there is some issue with bindings. I'll check it later.
I've tested with arch and it seems it works fine!

**Comment by IngoMeyer441** [comment]
It could also be a problem related to macOS. I need to fetch a mac to do some testing...

**Comment by aca** [comment]
@IngoMeyer441 
There's no issue for mac. My mistake. (But it didn't work before, don't know why it works now 😅)
Just patching this https://github.com/IngoMeyer441/tmux-easy-motion/pull/5 fix my issue.
