### ISSUE TITLE
Selection highlighting can be wrong with long lines

### ISSUE THREAD

**Issue by butwerenotthereyet** [IngoMeyer441/tmux-easy-motion#12]
If easy-motion is started in copy-mode when a selection (or block selection) is active, the selection is discarded.  It would be neat to create selection using tmux-easy-motion to define the beginning and end.

**Comment by IngoMeyer441** [comment]
Do you have an example? I am a bit suprised since I use tmux-easy-motion often to extend an active selection. Before commit 228a073b855e2aa8c2d4e6c29b4dcbb72c9880a4 the selection was cleared when the current pane was zoomed but this should be fixed now.

**Comment by butwerenotthereyet** [comment]
Not able to show example of original problem now, but here are some related issues.  Maybe original problem has the same cause?

Cat a big file with long lines and go to top-left:
![0](https://user-images.githubusercontent.com/58348703/106847576-087b6780-6664-11eb-8e57-d9cf027bbd77.png)

Start target-letter mode (`s` `s` in the image):
![1](https://user-images.githubusercontent.com/58348703/106847694-44aec800-6664-11eb-8571-768aedd5fe0f.png)

Target a letter (`c`)
![2](https://user-images.githubusercontent.com/58348703/106847758-69a33b00-6664-11eb-8ac3-da1c405e9b46.png)

Choose the first target letter (`n` in the image):
![3](https://user-images.githubusercontent.com/58348703/106847796-80499200-6664-11eb-8dff-c7bb9a8a56eb.png)

💥 The wrapping is funny.  Did new characters get inserted rather than original characters being replaced?

Choose the second letter (`s` in the image):
![4](https://user-images.githubusercontent.com/58348703/106847960-d28ab300-6664-11eb-938d-af4ec4269a6d.png)

Start a selection (`space` in the image):
![5](https://user-images.githubusercontent.com/58348703/106848035-f3eb9f00-6664-11eb-8c40-529107672961.png)

Move a bit to see that selection is active (`f` `space` in the image):
![6](https://user-images.githubusercontent.com/58348703/106848097-1c739900-6665-11eb-9d86-c21289cbf285.png)

Start target-letter mode (`s` `s` in the image):
![7](https://user-images.githubusercontent.com/58348703/106848137-31e8c300-6665-11eb-9989-8d0607d1c2fa.png)

Target a letter (`l` in the image):
![8](https://user-images.githubusercontent.com/58348703/106848447-d965f580-6665-11eb-98d9-b0d3ffcfa35d.png)

Choose the first target letter (`f` in the image):
![9](https://user-images.githubusercontent.com/58348703/106848498-f0a4e300-6665-11eb-9216-c019af0fda2a.png)

Choose the second letter (`e` in the image):
![10](https://user-images.githubusercontent.com/58348703/106848537-00242c00-6666-11eb-896c-074d42419441.png)

💥 Highlighting is funny.  Is this from long lines getting longer?

Move up a line or two:
![11](https://user-images.githubusercontent.com/58348703/106848622-2649cc00-6666-11eb-9dbc-6419f4ec8f37.png)
![12](https://user-images.githubusercontent.com/58348703/106848626-28138f80-6666-11eb-8ebc-28132a6add64.png)

Then move down:
![13](https://user-images.githubusercontent.com/58348703/106848665-3cf02300-6666-11eb-8481-002c7eeac8cf.png)

💥 Highlighting is funnier.

Moving down over the end of the fake highlighting fix the problem:
![14](https://user-images.githubusercontent.com/58348703/106848740-65781d00-6666-11eb-9a23-5ade35cba925.png)
![15](https://user-images.githubusercontent.com/58348703/106848747-67da7700-6666-11eb-9166-6aa7d87fd3d3.png)

**Comment by butwerenotthereyet** [comment]
Updated title to be accurate.

**Comment by IngoMeyer441** [comment]
Ok, I think I found the problem. Multiple targets with the same text position were printed one after another which led to a text shift (for example when searching for `c` in `occaecat`). Now targets with the same text position are sorted and only the first target is shown on screen (commit a8d4ddc68eaca07a79704aca082a85687d629984).

**Comment by IngoMeyer441** [comment]
That should also fix the weird selection rendering issues.

**Comment by butwerenotthereyet** [comment]
This is fantastic!  Thank you!!  (I repeated the steps above and the bug is fixed.)  The long line extending had other effects too like making tmux-easymotion hard to use when scrolled--that's fixed too!

**Comment by IngoMeyer441** [comment]
Thanks for reporting and testing!

**Comment by IngoMeyer441** [comment]
Hopefully, it is now ready for use in the daily workflow. :smile:
