### ISSUE TITLE
Causes Bell tone on iTerm/Kitty

### ISSUE THREAD

**Issue by jam1015** [IngoMeyer441/tmux-easy-motion#14]
When I use this plugin in iterm or Kitty the 'boop' noise/bell that sounds when you do something wrong sounds when I use this plugin.  It doesn't happen in Alacritty.

**Comment by IngoMeyer441** [comment]
Hey,
I ran some tests on a fresh Catalina installation with tmux 3.2a from Homebrew and iTerm2. Until now, I cannot reproduce the bell tone. How did you install the plugin? Could you please send your `.tmux.conf`?

**Comment by jam1015** [comment]
Hey! I found the problem.  I had both `set -g monitor-activity on` and `set -g visual-activity off`, which caused the bell.
