### ISSUE TITLE
Improve docs on how to invoke bidirectional motion

### ISSUE THREAD

**Issue by mikehaertl** [IngoMeyer441/tmux-easy-motion#18]
Just tried your plugin and it really looks very promising.

I just don't get how to invoke a bidirectional motion. I may be stupid but I read through the README a couple of times now and don't get the meaning of this:

> bd-w (bd-* -> bidirectional motion)
> bd-W
> bd-e
> bd-E
> bd-j

Obviously `bd-` does not mean that I should press `b` then `d` and so on as `b` already invokes a word-wise back motion. But what does it mean? How do I invoke bidirectional motion?

**Comment by IngoMeyer441** [comment]
Hey and thanks for trying my tmux plugin. All key bindings are configurable and in the default setup, the bidirectional motions are not bound to any key. The [key-bindings section](https://github.com/IngoMeyer441/tmux-easy-motion#key-bindings) explains how to configure key bindings or how to set a default motion if you only want to use `bd-w`, for example.

But I agree with you, that the documentation could be more clear on this.

**Comment by mikehaertl** [comment]
I see, thanks for the clarification. Maybe really worth a note in the README?

**Comment by IngoMeyer441** [comment]
I have added a note a few seconds ago in commit ba3b60ada7cb96bb0af9978e9bb43e1982665c71. :smiley: Thanks for pointing me to this.

**Comment by mikehaertl** [comment]
Looks good, thanks!
