### ISSUE TITLE
three questions: mode visualization / highlighting all words / `jj` wrong behavior

### ISSUE THREAD

**Issue by ywpkwon** [IngoMeyer441/tmux-easy-motion#2]
Hi. Thanks for the awesome project! I've been a huge fan of vim easy motion, and I was using `tmux-jump`. It is great but I was feeling a bit about its limitation and this seems a better fit for me! Thanks.

I have three questions at this moment (my prefix is `C-space`):

1. I'm using `Space` for another purpose. So I switch it to `set -g @easy-motion-prefix "]"`. When I enter the easy motion mode (`C-Space ]`), I can't see any visual sign that it is easy motion now and waiting for a key. 
   I realize that when target keys are highlighted (`C-Space ] b`), it shows `[easy-motion]` status, wouldn't it be helpful to visualize when up to `C-Space ]` and visualize users somehow it is now easy motion mode?

2. I realized that `b` and `w` highlight earlier and after words. Is there a key to highlight all words (ie, both directions for convenience)?
3. In copy mode, if I push `jj`, it somehow acts like the `]j` (ie, easy motion's `j`). For `jj`, I would just want to go down two lines. Why it activates easy motion? For example, 'kk' works just normally. Is it a bug? or my setting problem?

**Comment by IngoMeyer441** [comment]
Thanks for trying my plugin. :slightly_smiling_face: I also use vim-easymotion every day and therefore I wanted a tmux plugin which behaves like the vim original.

Some answers to your questions:

1. The `[easy-motion]` status is actually an implementation detail and was not meant as an status indicator (this plugin creates a temporary tmux window which is called `[easy-motion]` to save the user's active pane so it can be restored after easy-motion finished). However, I could add a verbose option and print status messages in the tmux status bar. Do you use a status bar plugin like [tmux-powerline](https://github.com/erikw/tmux-powerline)? We could also create a custom segment for such a status bar.

2. Currently not. But I think it would be a good idea to add more motions and make all motion keys configurable (just like in vim-easymotion).

3. Odd, I have no idea why this happens. I ran a test with a minimal `tmux.conf`:
   ```tmux
   set -g @easy-motion-prefix "]"
   unbind C-b
   set -g prefix C-Space

   run './easy_motion.tmux'
   ```
   but could not reproduce your problem. Is a maybe related to another setting?

**Comment by IngoMeyer441** [comment]
Commit 652c0c3b4081069a8f2bf98e5db60e6840d1e0b2 adds a verbose mode. It can be configured with
```
set -g @easy-motion-verbose "no"
```
and uses the tmux status line to display messages. Is this useful for you?

I also added bidirectional motions (see #4).
