### ISSUE TITLE
Proposal: Start easymotion without motions.

### ISSUE THREAD

**Issue by aca** [IngoMeyer441/tmux-easy-motion#4]
So happy with this plugin! Thanks!

There's many "movement" options for easymotion but I personally use only "word" movement (`<Plug>(easymotion-overwin-w)`).

I want to archive the same with this plugin. But it seems that I have to choose motion to get into the easymotion mode. `<prefix> + <space> + w`.

It would be great if I can set default motion and start easymotion mode with just `<prefix> + <space>`.

And also highlighting all words as https://github.com/IngoMeyer441/tmux-easy-motion/issues/2 mentioned.

**Comment by IngoMeyer441** [comment]
Is added to my todo list. :wink:

**Comment by IngoMeyer441** [comment]
However, it could be a bit tricky to implement a overwin motion because this plugin only uses one tmux pane currently.

**Comment by aca** [comment]
I fully understand. It would be just fine to be able to move inside pane. thx

**Comment by 123subhadeep** [comment]
This is exactly what I was looking for as well, right now we need to always specify a motion, which has a couple of drawbacks:
1. One extra keystroke
2. Need to spend some mental effort: need to first decide whether the word I am trying to jump above or below the cursor.

So it will be great if we can just mark all the words on the screen for jump on <prefix> + <space> (or some other configurable key)

**Comment by aca** [comment]
@123subhadeep 
For now you might want to try this key binding.
```
bind-key -T prefix w switch-client -T easy-motion\; run-shell -b "/Users/rok/.tmux/plugins/tmux-easy-motion/scripts/easy_motion.sh 'B'"
```

**Comment by 123subhadeep** [comment]
@aca Thanks for the tip, it saved me a keystroke ! However, it only marks the words that are above the cursor. Do you know if there's a way to mark all the words on the screen ? Thanks again !

**Comment by IngoMeyer441** [comment]
Sorry for the delay. I work on configurable key bindings and more motions (especially bidrectional motions), but currently I have not so much free time. I think in a few days I can push it to `develop`.

**Comment by IngoMeyer441** [comment]
Commit 5776bd49280f68ed5437e14c9177bfe51751dacd adds bidirectional motions and commit 214802a09c0194c095d447f0bca5f03f0285921f a default motion. Now you can simply configure
```
set -g @easy-motion-default-motion "bd-w"
```
to highlight all words in both directions as soon as the easy motion prefix key is pressed. See the [README](https://github.com/IngoMeyer441/tmux-easy-motion/blob/master/README.md#key-bindings) for more details how key bindings can be configured.

**Comment by IngoMeyer441** [comment]
I close this issue since I think it is fixed. Feel free to reopen.
